services:
  - type: web
    name: vinals-feed
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: IG_USERNAME
        value: vinals1906
      - key: LI_SLUG
        value: vinalsgrupo
      - key: REFRESH_MS
        value: "28800000"
      - key: IG_BUSINESS_ID
        value: "17841403980877254"
      - key: IG_ACCESS_TOKEN
        sync: false
